import { app, BrowserWindow, ipcMain, session } from "electron";
import * as fs from "fs";
import * as https from "https";
import * as path from "path";
import "dotenv/config";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// ---------------------------------------------------------------------------
// Kara moe API client (main process only — the renderer never touches the
// network directly, following Electron security best practices).
// ---------------------------------------------------------------------------

const API_BASE = process.env.API_URL + "/api";
const MEDIA_BASE = process.env.API_URL;

export interface TagRef {
  tid: string;
  name: string;
  short?: string | null;
}

export interface LyricsInfo {
  default?: boolean;
  version?: string;
  filename?: string;
}

/** A song as returned by the Kara moe API (search + single-song endpoints). */
export interface Song {
  kid: string;
  titles: Record<string, string>;
  titles_default_language?: string | null;
  hardsubbed_mediafile?: string | null;
  mediafile?: string | null;
  duration?: number | null; // seconds
  mediasize?: number | null; // bytes
  year?: number | null;
  songname?: string | null;
  series?: TagRef[];
  singers?: TagRef[];
  songtypes?: TagRef[];
  langs?: TagRef[];
  lyrics_infos?: LyricsInfo[];
}

export interface SearchResponse {
  infos: { count: number; from: number; to: number };
  content: Song[];
}

/** A catalog entry persisted locally for a downloaded song. */
export interface CatalogEntry {
  kid: string;
  title: string;
  series: string;
  singer: string;
  duration: number | null; // seconds
  file: string; // filename of the hardsub video inside the catalog dir
  size: number | null; // bytes
  downloadedAt: string; // ISO date
}

/** A row shown in the search results list. */
export interface SearchRow {
  kid: string;
  title: string;
  series: string;
  singer: string;
  duration: number | null;
  size: number | null;
}

// ---------------------------------------------------------------------------
// Local catalog storage (~/.config/vocal-vanish/kara-catalog)
// ---------------------------------------------------------------------------

const CATALOG_DIR = (): string =>
  path.join(app.getPath("userData"), "kara-catalog");

const CATALOG_INDEX_FILE = (): string =>
  path.join(CATALOG_DIR(), "catalog.json");

function ensureCatalogDir(): void {
  fs.mkdirSync(CATALOG_DIR(), { recursive: true });
}

function readIndex(): Record<string, CatalogEntry> {
  try {
    const raw = fs.readFileSync(CATALOG_INDEX_FILE(), "utf8");
    return JSON.parse(raw) as Record<string, CatalogEntry>;
  } catch {
    return {};
  }
}

function writeIndex(index: Record<string, CatalogEntry>): void {
  ensureCatalogDir();
  fs.writeFileSync(CATALOG_INDEX_FILE(), JSON.stringify(index, null, 2));
}

function songToRow(song: Song): SearchRow {
  const title =
    (song.titles_default_language &&
      song.titles[song.titles_default_language]) ||
    Object.values(song.titles)[0] ||
    song.songname ||
    "Untitled";
  return {
    kid: song.kid,
    title,
    series: song.series?.map((s) => s.name).join(", ") || "",
    singer: song.singers?.map((s) => s.name).join(", ") || "",
    duration: song.duration ?? null,
    size: song.mediasize ?? null,
  };
}

// ---------------------------------------------------------------------------
// HTTP helpers (Node's https module — no extra dependencies).
// ---------------------------------------------------------------------------

function httpGetJson<T>(url: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const req = https.get(
      url,
      { headers: { "User-Agent": "vocal-vanish/1.0" } },
      (res) => {
        if (
          !res.statusCode ||
          (res.statusCode >= 300 && res.statusCode < 400)
        ) {
          // Follow a single redirect (e.g. /api/karas/{kid}/hardsub -> /hardsubs/*.mp4)
          const loc = res.headers.location;
          res.resume();
          if (loc) {
            httpGetJson<T>(new URL(loc, url).toString()).then(resolve, reject);
            return;
          }
        }
        if (!res.statusCode || res.statusCode >= 400) {
          const err = new Error(`HTTP ${res.statusCode} for ${url}`);
          res.resume();
          reject(err);
          return;
        }
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => (body += chunk));
        res.on("end", () => {
          try {
            resolve(JSON.parse(body) as T);
          } catch (e) {
            reject(
              new Error(`Invalid JSON from ${url}: ${(e as Error).message}`),
            );
          }
        });
      },
    );
    req.on("error", reject);
  });
}

/**
 * Stream a file download to disk, reporting progress. Returns the final file
 * size in bytes. Throws on HTTP error or network failure.
 */
function downloadFile(
  url: string,
  destPath: string,
  onProgress: (received: number, total: number | null) => void,
): Promise<number> {
  return new Promise((resolve, reject) => {
    const req = https.get(
      url,
      { headers: { "User-Agent": "vocal-vanish/1.0" } },
      (res) => {
        // Follow redirects transparently.
        if (
          res.statusCode &&
          res.statusCode >= 300 &&
          res.statusCode < 400 &&
          res.headers.location
        ) {
          res.resume();
          const next = new URL(res.headers.location, url).toString();
          downloadFile(next, destPath, onProgress).then(resolve, reject);
          return;
        }
        if (!res.statusCode || res.statusCode >= 400) {
          res.resume();
          reject(new Error(`HTTP ${res.statusCode} downloading ${url}`));
          return;
        }
        const total = res.headers["content-length"]
          ? parseInt(res.headers["content-length"], 10)
          : null;
        let received = 0;
        const out = fs.createWriteStream(destPath);
        res.on("data", (chunk: Buffer) => {
          received += chunk.length;
          onProgress(received, total);
        });
        res.pipe(out);
        out.on("error", reject);
        out.on("finish", () => resolve(received));
      },
    );
    req.on("error", reject);
  });
}

// ---------------------------------------------------------------------------
// IPC handlers
// ---------------------------------------------------------------------------

function registerIpc(): void {
  // Search the Kara moe database. `mode` selects how `query` is interpreted:
  //   text -> plain "filter" param (matches title/series/singer)
  //   year -> structured q="y:<year>"
  //   kid  -> structured q="k:<kid>"
  ipcMain.handle(
    "kara:search",
    async (
      _e,
      params: {
        query: string;
        from: number;
        size: number;
        mode?: "text" | "year" | "kid";
      },
    ) => {
      const url = new URL(`${API_BASE}/karas/search`);
      const q = (params.query || "").trim();
      const mode = params.mode || "text";
      if (q) {
        if (mode === "year") url.searchParams.set("q", `y:${q}`);
        else if (mode === "kid") url.searchParams.set("q", `k:${q}`);
        else url.searchParams.set("filter", q);
      }
      url.searchParams.set("from", String(params.from));
      url.searchParams.set("size", String(params.size));
      const data = await httpGetJson<SearchResponse>(url.toString());
      return {
        count: data.infos?.count ?? 0,
        rows: (data.content || []).map(songToRow),
      };
    },
  );

  // List locally downloaded songs.
  ipcMain.handle("kara:catalog", async () => {
    const index = readIndex();
    return Object.values(index).sort((a, b) =>
      b.downloadedAt.localeCompare(a.downloadedAt),
    );
  });

  // Download a song's hardsub video into the local catalog.
  ipcMain.handle(
    "kara:download",
    async (e, kid: string): Promise<CatalogEntry> => {
      const sender = e.sender;
      ensureCatalogDir();

      // Fetch full song metadata to get title/series/duration + hardsub filename.
      const song = await httpGetJson<Song>(
        `${API_BASE}/karas/${encodeURIComponent(kid)}`,
      );
      if (!song || !song.hardsubbed_mediafile) {
        throw new Error("This song has no downloadable hardsub media.");
      }

      const row = songToRow(song);
      const fileName = song.hardsubbed_mediafile; // e.g. "<kid>.<size>.<hash>.mp4"
      const finalPath = path.join(CATALOG_DIR(), fileName);
      const tmpPath = `${finalPath}.part`;

      // Clean up any stale partial file from a previous interrupted download.
      try {
        if (fs.existsSync(tmpPath)) fs.unlinkSync(tmpPath);
      } catch {
        /* ignore */
      }

      const mediaUrl = `${MEDIA_BASE}/hardsubs/${encodeURIComponent(fileName)}`;
      await downloadFile(mediaUrl, tmpPath, (received, total) => {
        sender.send("kara:download-progress", { kid, received, total });
      });

      // Atomically move the completed file into place.
      fs.renameSync(tmpPath, finalPath);

      const index = readIndex();
      const entry: CatalogEntry = {
        kid: song.kid,
        title: row.title,
        series: row.series,
        singer: row.singer,
        duration: row.duration,
        file: fileName,
        size: row.size,
        downloadedAt: new Date().toISOString(),
      };
      index[song.kid] = entry;
      writeIndex(index);
      return entry;
    },
  );

  // Stream a catalog video to the renderer. The renderer's <video>/video.js
  // cannot load file:// URLs directly in dev mode (the page is served from the
  // webpack-dev-server HTTP origin, which is not allowed to fetch local files),
  // so we pipe the bytes back over IPC and let the renderer wrap them as a
  // fetch-compatible body. This works identically in dev and production.
  ipcMain.on("kara:media-stream", (e, kid: string) => {
    const index = readIndex();
    const entry = index[kid];
    if (!entry) {
      e.reply("kara:media-data", {
        ok: false,
        error: `Song ${kid} is not in the local catalog.`,
      });
      return;
    }
    const p = path.join(CATALOG_DIR(), entry.file);
    if (!fs.existsSync(p)) {
      e.reply("kara:media-data", {
        ok: false,
        error: "Video file is missing from disk.",
      });
      return;
    }
    const stream = fs.createReadStream(p);
    stream.on("data", (chunk: Buffer) =>
      e.sender.send("kara:media-data", { chunk }),
    );
    stream.on("error", (err: Error) =>
      e.reply("kara:media-data", { ok: false, error: err.message }),
    );
    stream.on("end", () => e.reply("kara:media-data", { ok: true }));
  });

  // Delete a song (video file + catalog entry).
  ipcMain.handle("kara:delete", async (_e, kid: string) => {
    const index = readIndex();
    const entry = index[kid];
    if (entry) {
      try {
        fs.unlinkSync(path.join(CATALOG_DIR(), entry.file));
      } catch {
        /* file may already be gone */
      }
      delete index[kid];
      writeIndex(index);
    }
    return true;
  });
}

// ---------------------------------------------------------------------------
// Content Security Policy
// ---------------------------------------------------------------------------

/**
 * Electron applies a restrictive default CSP (`default-src 'self' 'unsafe-inline' data:`)
 * that blocks the `blob:` media URLs we use to play downloaded videos. We set an
 * explicit, appropriate policy on the session instead: media is allowed from blob:
 * and file:, while scripts stay locked to 'self' in production.
 *
 * In development, webpack-dev-server's HMR client evaluates its code via `eval`,
 * so we relax script-src to allow 'unsafe-eval' (and inline) — otherwise the app
 * shows a black screen. This relaxation is dev-only; production keeps the strict
 * 'self' script policy.
 */
function applyCsp(): void {
  const isDev = !app.isPackaged;
  const csp = [
    "default-src 'self'",
    isDev
      ? "script-src 'self' 'unsafe-inline' 'unsafe-eval'"
      : "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "media-src 'self' blob: file:",
    "font-src 'self' data:",
    "connect-src 'self' https://kara.moe",
  ].join("; ");

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [csp],
      },
    });
  });
}

// ---------------------------------------------------------------------------
// Window management
// ---------------------------------------------------------------------------

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 720,
    width: 1080,
    minWidth: 760,
    minHeight: 480,
    backgroundColor: "#111318",
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // Security best practices: no Node integration in the renderer; all
      // privileged work goes through the contextBridge in preload.ts.
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

app.on("ready", () => {
  applyCsp();
  registerIpc();
  createWindow();
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
